[package]
name = "pw"
version = "0.1.0"
edition = "2021"

[dependencies]
clap      = { version = "4", features = ["derive"] }
rpassword = "7"
ring      = { version = "0.17", features = ["alloc"] }
serde     = { version = "1", features = ["derive"] }
serde_json = "1"
dirs      = "5"
zeroize   = "1"
rand      = "0.8"
base64    = "0.22"
copypasta = "0.10.2"
anyhow    = "1"
tracing   = "0.1"
arrayref = "0.3"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
